services:
  app:
    image: frontend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile 
    volumes:
      - ./:/app 
    ports:
      - 5000:3000
    container_name: frontend-dev-in-container # This will name the container hello-front-dev