version: '3.8'
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    container_name: nginx-layer
    depends_on:
      - frontend
      - node
      - redis
      - mongodb
  frontend: 
    build: 
      context: ./todo-frontend/
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    environment: 
      - REACT_APP_BACKEND_URL= http://localhost:8080/api
  node: 
    build: 
      context: ./todo-backend/
      dockerfile: Dockerfile  
    volumes:
      - ./todo-backend:/app
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - redis
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "3456:27017"
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=the_database
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ['redis-server', '--appendonly', 'yes'] 
    volumes:
      - ./todo-backend/redis_data:/data
volumes:
  mongo_data: