version: "3.8"
services:
  monogodb:
    image: mongo
    ports:
      - "3456:27017"
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=the_database
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  mongo_data: 